### ISSUE TITLE
1.2 Declaração de posição de produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ChaosManager#11]
Essa declaração está muito genérica.
1. Gerencia os principais aspectos de uma campanha de rpg de mesa. QUE ASPECTOS?
2. Unifica as principais ferramentas do rpg de mesa online... QUE FERRAMENTAS?

![image](https://github.com/mdsreq-fga-unb/2023.2-ChaosManager/assets/68402547/58f9e7a9-4412-42d3-9c8a-750ef645bcfe)

**Comment by PedroEduardoSS** [comment]
Adicionei parênteses para exemplificar os aspectos e as ferramentas
