### ISSUE TITLE
1.3 Objetivos do produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-ChaosManager#12]
"Apresenta um único sistema de regra brasileiro com ferramentas acessíveis e que pode ser usado para qualquer tipo de história, campanha e mundos, com todas as ferramentas necessárias para gerenciar uma campanha de rpg de mesa, tanto para mestres quanto para jogadores."

**CONSIDERAÇÕES:**
- A ferramenta é um meio para se atingir um objetivo. Qual é o objetivo?

**Comment by PedroEduardoSS** [comment]
Mantive o que já estava, mas adicionei uma linha escrito "Objetivo: Unificar ferramentas de um rpg de mesa citados na declaração do produto, por meio de um único sistema de regras."
