### ISSUE TITLE
Tela principal

### ISSUE THREAD

**Issue by larigs** [mdsreq-fga-unb/2023.2-ChaosManager#73]
não sei exatamento a melhor forma aqui ja que imaginei a tela principal sendo a ficha do jogador, sugestões são aceitas, a minha abaixo:
- apenas uma "biblioteca" (uma lista)  contendo todas as fichas, onde o jogador seleciona a que ele quer e é redirecionado pra tela da ficha de personagem correspondente 
- Se o acesso for do mestre, além das fichas de jogadores, mostrar as fichas de NPC e a tela do gerenciador de combate

- [x] fazer a conexão do acessar campanha com a tela principal

**Comment by PedroEduardoSS** [comment]
precisa terminar o redirecionamento para as fichas
